CREATE TABLE "user" (
  "username" varchar PRIMARY KEY,
  "hashed_password" varchar NOT NULL,
  "password_changedat" timestamptz NOT NULL DEFAULT '0001-01-01 00:00:00Z',
  "email" varchar UNIQUE NOT NULL,
  "nickname" varchar,
  "create_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "article" (
  "article_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "author_username" varchar NOT NULL,
  "content" varchar NOT NULL,
  "create_at" timestamptz NOT NULL DEFAULT (now()),
  "changed_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "article" ADD FOREIGN KEY ("author_username") REFERENCES "user" ("username");
